### ISSUE TITLE
Load Removal?

### ISSUE THREAD

**Issue by AlbertHamik** [christofsteel/pyautosplit#4]
Is it possible for this tool to support load removal?

**Comment by InfoTeddy** [comment]
Out of scope.

If you want to remove the fake loading screen, then use the 2.3 beta on Steam (VVVVVV's source code got released!), or if you want to stay on 2.2, then look [at this](https://tolp.nl/forum/index.php?topic=2549.0).

But also, as far as I know doing either of these is technically not allowed by the speedrunning rules, if you're planning on submitting to the speedrun.com leaderboards.

**Comment by AlbertHamik** [comment]
Wait this tool pertains to a particular game? I was only speaking of general support for pausing and unpausing the timer for load removal.

**Comment by InfoTeddy** [comment]
Yeah, it was originally written for VVVVVV (which has an unusual memory layout in that every single thing is allocated on the stack, so this tool was created to read memory off the stack). Sorry for misunderstanding.

**Comment by AlbertHamik** [comment]
No problem. I was glancing into the matter of load removal as I'm using a VM emulator in Linux for a game and I was curious on if there was anything out there on Linux for scripting load removals for any timers.

**Comment by christofsteel** [comment]
Hi,
so for context. Yes initially this was purely for VVVVVV, but I made it more general since then. Load removal was not on my radar, but can be easily added.
The way this works is entirely trigger based. pyautosplit watches the memory of (currently) exactly one process and sends a command to the network component of LiveSplit (and optionally can set debugger like break points to calculate some memory locations), I do not know how well this works through a virtual machine, though... you would have to know the memory layout of the VM and of the Application, but in theory this should be manageable.

**Comment by christofsteel** [comment]
This is now implemented in 53179a64c6cd3f38cfdb4d301dea723660d21228.
Mind you this is the develop branch, sometimes things break there (but I try to test everything I push there)
